steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - gcloud 
      - functions 
      - deploy 
      - download_kaggle_data
      - --gen2
      - --runtime=python310
      - --trigger-http
      - --allow-unauthenticated
      - --region=${_REGION}
      - --source=src/utils/download_kaggle_data
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},BUCKET=${_BUCKET}
      - --timeout=540s
      - --memory=1024MB
      # you need to deploy the `kaggle-json` secrets first by running `gcloud secrets create kaggle-json --data-file=kaggle.json`
      - --set-secrets=${_SECRET_NAME}=projects/${_PROJECT_ID}/secrets/${_SECRET_NAME}:latest


options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: gp-461213
  _REGION: us-central1
  _BUCKET: air-pollution-data-my
  _SECRET_NAME: kaggle-json
