steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - gcloud 
      - functions 
      - deploy 
      - ${_FUNCTION_NAME}
      - --runtime python310
      - --trigger-http
      - --allow-unauthenticated
      - --region=${_REGION}
      - --source=${_SOURCE}
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},BUCKET=${_BUCKET}
      - --timeout=540s
      - --memory=1024MB

substitutions:
  _SOURCE : src/utils/download_and_upload
  _FUNCTION_NAME: download_and_upload
  _PROJECT_ID: gp-461213
  _REGION: us-central1
  _BUCKET: air-pollution-data-my
