steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - |
        gsutil -m rsync -d -r ${_SRC_DIRECTORY}/ gs://${_SRC_BUCKET}/${_SRC_DIRECTORY}/

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SRC_BUCKET: us-central1-airflow-bucket
  _SRC_DIRECTORY: src