steps:
  # Step 1: Deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - download_kaggle_data
      - --gen2
      - --runtime=python310
      - --trigger-http
      - --region=${_REGION}
      - --source=src/scripts/download_kaggle_data
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},BUCKET=${_BUCKET}
      - --timeout=540s
      - --memory=1024MB
      - --set-secrets=${_SECRET_NAME}=projects/${_PROJECT_ID}/secrets/${_SECRET_NAME}:latest
      - --allow-unauthenticated
      - --ingress-settings=all

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: gp-461213
  _PROJECT_NUM: '1000028997311'
  _REGION: us-central1
  _BUCKET: air-pollution-data-my
  _SECRET_NAME: kaggle-json