steps:
  # sync to local src/ folder to google cloud storage
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - |
        gsutil -m rsync -d -r src gs://${_SRC_BUCKET}/src

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SRC_BUCKET: us-central1-airflow-bucket